### ISSUE TITLE
Expected Value and variance - language review/correction

### ISSUE THREAD

**Issue by benjamin-jacobson** [learn-co-curriculum/dsc-probability-mass-function#1]
Under the heading Expected Value and variance, it says: "... two descriptive quantities you're interested in: the expected value and the mean.".I think they mean expected value and variance?

Nice work Umar Khan!

**Comment by LoreDirick** [comment]
@benjamin-jacobson thank you! I think you're right - it makes more sense, at least. I corrected it.
