### ISSUE TITLE
The Probability Mass Function (PMF)

### ISSUE THREAD

**Issue by scarlettvalentin** [learn-co-curriculum/dsc-probability-mass-function#3]
## Link to Canvas

https://learning.flatironschool.com/courses/7297/assignments/270642?module_item_id=651359

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ x] Layout/rendering issue
- [ ] Instructions unclear
- [ x] Other (explain below)

### Source

```
| Formula     | Name     | `i=0`  | `i=1`  | `i=2`  | `i=3`  | `i=4`  | $\sum$ |
| ----------- | -------- | ------ | ------ | ------ | ------ | ------ | ------ |
|<img width=100/>|<img width=150/>|<img width=80/>|<img width=80/>|<img width=80/>|<img width=80/>|<img width=80/>|<img width=100/>|
| $x_i$       | outcome   | 1      | 2      | 3      | 4      | 5      |        |
| $p(x_i)$    | probability | $0.31$ | $0.31$ | $0.15$ | $0.08$ | $0.15$ | $1$ (i.e. $P(\Omega)$) 
| $p(x_i)x_i$ |  | $0.31$  | $0.62$  | $0.46$ | $0.31$  |$0.77$   |  $2.46$ (i.e. $\mu$)  |
| $(x_i-\mu)^2$| squared difference from the mean | $2.14$ | $0.213$ | $0.300$ | $2.37$ | $6.44$ |
| $ p(x_i)(x_i-\mu)^2$|  | $0.657$ | $0.0655$ | $0.0446$ |$0.182$ | $0.991$ | $1.94$ (i.e. $\sigma^2$) |


```

### Concern

This code creates a table with the first row intended to be images but there are no images.

An additional issue with this lesson and a few proceeding in this section is that they reference previous statistical lessons but the previous statistical lessons are not in Canva. 

## What OS Are You Using?

- [x ] OS X
- [ ] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thank you for making us aware of this one too, we'll take a look.

**Comment by bpurdy-ds** [comment]
The `<img width=100/>` just refers to a spacing, it is actually not supposed to be an image. (That is confusing, but it makes it look cleaner in the python notebook)
And, I cleaned up the verbiage. Thanks again for your attentiveness.
